name: Cypress tests
on:
  push:
    branches:
      - testing-cyp
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # E2E
      - name: Cypress run
        uses: cypress-io/github-action@v6

