on:
  push:
    tags:
      - 'v*.*.*'  # Trigger only when pushing a version tag, e.g., v1.0.0

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build application
        run: npm run build

      - name: Package application
        run: npx electron-builder --linux  # Build for Linux
        env:
          GH_TOKEN: ${{ secrets.SECRET_1 }}

      - name: Upload artifact
        id: upload_ubuntu
        uses: actions/upload-artifact@v4
        with:
          name: Todometer-ubuntu
          path: dist/

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build application
        run: npm run build

      - name: Package application
        run: npx electron-builder --mac  # Build for macOS
        env:
          GH_TOKEN: ${{ secrets.SECRET_1 }}

      - name: Upload artifact
        id: upload_macos
        uses: actions/upload-artifact@v4
        with:
          name: Todometer-macos
          path: dist/

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build application
        run: npm run build

      - name: Package application
        run: npx electron-builder --win  # Build for Windows
        env:
          GH_TOKEN: ${{ secrets.SECRET_1 }}

      - name: Upload artifact
        id: upload_windows
        uses: actions/upload-artifact@v4
        with:
          name: Todometer-windows
          path: dist/

  release:
    needs: [build-ubuntu, build-macos, build-windows]  # Upewniamy się, że build zakończy się przed tworzeniem release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Pobieramy artefakty z poprzednich jobów
      - name: Download Ubuntu artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build-ubuntu.outputs.upload_ubuntu }}  # Odwołanie do uploadu Ubuntu przez zmienną

      - name: Download MacOS artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build-macos.outputs.upload_macos }}

      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build-windows.outputs.upload_windows }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            Todometer-ubuntu/*
            Todometer-macos/*
            Todometer-windows/*
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
