name: CI/CD for Todometer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout kodu
      - name: Checkout repository
        uses: actions/checkout@v4

      # Instalacja Node.js, zmiana na 20 a było 23
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' 

# Konfiguracja cache dla zależności npm
      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-

      # Instalacja zależności
      - name: Install dependencies
        run: npm install

      # Testy jednostkowe (prawdopodobnie)
      - name: Run unit tests
        run: npm test

      # Budowanie aplikacji
      - name: Build app
        run: npm run build

      - name: Npm audit test #w ramach SCA
        continue-on-error: true
        run: npm install --package-lock-only && npm audit --json > audit-report.json
       # run: npm audit --json > audit-report.json

      - name: Upload audit report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: npm-audit-report
          path: audit-report.json

#Tego jeszcze nie jestem pewna czy tak zostanie czy inny linter użyje
      - name: Super-linter
        continue-on-error: true
        uses: super-linter/super-linter@v7.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_1 }}
          
  other_tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
           npm-

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v3.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
              -Dsonar.organization=cc1xmn4gt7
              -Dsonar.projectKey=kmnxa_tdm
              -Dsonar.sources=.
              
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run start #ewentualnie builda dodam, ale już był wyżej

        
